python_test:
  - 'tests/**'
  - 'tools/**'
  - 'edumfa/**/*.py'
  - '.github/workflows/python.yml'
  - '.github/filters.yml'
  - 'edumfa-manage'
  - 'requirements.txt'
  - 'setup.py'
  - 'pyproject.toml'
