#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# License:  AGPLv3
# This file is part of eduMFA. eduMFA is a fork of privacyIDEA which was forked from LinOTP.
# Copyright (c) 2024 eduMFA Project-Team
# Previous authors by privacyIDEA project:
#
# 2020 Henning Hollermann <henning.hollermann@netknights.it>
# 2017 Diogenes S. Jesus
# 2014 - 2020 Cornelius Kölbel <cornelius.koelbel@netknights.it>
#
# (c) Cornelius Kölbel
#
# This code is free software; you can redistribute it and/or
# modify it under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE
# License as published by the Free Software Foundation; either
# version 3 of the License, or any later version.
#
# This code is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU AFFERO GENERAL PUBLIC LICENSE for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with this program.  If not, see <http://www.gnu.org/licenses/>.
# ./manage.py db init
# ./manage.py db migrate
# ./manage.py create_tables
#

from edumfa.commands.manage.main import cli as manage_cli

if __name__ == '__main__':
    manage_cli()
