version: "3.8"

services:
  mariadb:
    image: docker.io/mariadb:lts-jammy
    restart: always
    networks:
       - edumfa-net
    volumes:
      - mariadb-data:/var/lib/mysql:rw
    environment:
      - MARIADB_PORT_NUMBER=3306
      - MARIADB_DATABASE=edumfa
      - MARIADB_USER=edumfa
      - MARIADB_PASSWORD=pass
      - MARIADB_ROOT_PASSWORD=pass

  edumfa:
    image: edumfa:latest
    restart: always
    networks:
       - edumfa-net
    ports:
      - "8000:8000"
    volumes:
      - ./docker-example/edumfa-setup.sh:/opt/edumfa/user-scripts/01-setup.sh:ro
      - ./docker-example/edumfa-config.conf:/opt/edumfa/policy.conf:ro
      - ./docker-example/edumfa.cfg:/opt/edumfa/edumfa.cfg:ro
      - edumfa-config:/etc/edumfa/:rw
    environment:
      - EDUMFA_CONFIGFILE=/opt/edumfa/edumfa.cfg
      - EDUMFA_ADMIN_USER=admin
      - EDUMFA_ADMIN_PASS=Passwort123
    depends_on:
      - mariadb

networks:
  edumfa-net:
    name: edumfa-network
    driver: bridge

volumes:
  edumfa-config:
  mariadb-data:
