"""add blacklist table for Passkey JWTs

Revision ID: 9cad6f046bd2
Revises: 2a74c6522937
Create Date: 2026-01-25 07:30:16.080336

"""

# revision identifiers, used by Alembic.
revision = "9cad6f046bd2"
down_revision = "2a74c6522937"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jwt_blacklist",
        sa.Column("expiration", sa.DateTime(), nullable=True),
        sa.Column("nonce", sa.Unicode(length=128), nullable=False, unique=True),
        sa.PrimaryKeyConstraint("nonce"),
        mysql_row_format="DYNAMIC",
    )
    op.create_index(
        op.f("ix_jwt_blacklist_expiration"),
        "jwt_blacklist",
        ["expiration"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_jwt_blacklist_expiration"), table_name="jwt_blacklist")
    op.drop_table("jwt_blacklist")
    # ### end Alembic commands ###
