#!/bin/bash
DATABASE=/etc/edumfa/users.sqlite
echo "create table users (id INTEGER PRIMARY KEY ,\
	username TEXT UNIQUE,\
	surname TEXT, \
	givenname TEXT, \
	email TEXT, \
	password TEXT, \
	description TEXT, \
	mobile TEXT, \
	phone TEXT);" | sqlite3 $DATABASE

cat <<END > /etc/edumfa/usersdb.install
{'Server': '/',
 'Driver': 'sqlite',
 'Database': '/etc/edumfa/users.sqlite',
 'Table': 'users',
 'Limit': '500',
 'Editable': '1',
 'Map': '{"userid": "id", "username": "username", "email":"email", "password": "password", "phone":"phone", "mobile":"mobile", "surname":"name", "givenname":"givenname", "description": "description"}'
}
END
chown edumfa $DATABASE

edumfa-manage resolver create localusers sqlresolver /etc/edumfa/usersdb.install
edumfa-manage realm create localsql localusers
