.\" Manpage for edumfa-fetchssh
.
.TH EDUMFA-FETCHSSH  1 "11 Oct 2015" "1.0" "eduMFA-fetchssh man page"
.SH NAME
eduMFA-fetchssh \- Fetch the defined ssh public keys from the eduMFA server.
.SH SYNOPSIS
eduMFA-fetchssh
.SH DESCRIPTION
This fetches the public SSH keys from the eduMFA server. This script is to be used with
the authorized_keys_command in the sshd_config of the OpenSSH server.

.SH INTERNET SOURCES
http://www.privacyidea.org
.SH SEE ALSO

.SH BUGS
No known bugs.
.SH AUTHOR
Peter Murr, privacyIDEA <info@privacyidea.org>
