#!/usr/bin/env python
#
#  2016-05-25 Cornelius Kölbel <cornelius.koelbel@netknights.it>
#
"""
This script reads the .google_authenticator files from all users in their
home directories and compiles an import file.
"""

import base64
import binascii
import os
import sys

tokens = []
num_tokens = 0
for user in os.listdir("/home/"):
    token_type = None
    try:
        num_tokens += 1
        f = open("/home/" + user + "/.google_authenticator")
        ga = f.readlines()
        f.close()
        seed = ga[0]
        seed_hex = binascii.hexlify(base64.b32decode(seed.strip()))
        for line in ga:
            if line.startswith('" TOTP_AUTH'):
                token_type = "totp"
            elif line.startswith('" HOTP_COUNTER'):
                token_type = "hotp"
        sys.stderr.write(f"++ Processing user {user}\n")
        if token_type == "totp":
            print(f"totp{num_tokens:04d}{user}, {seed_hex}, totp, 6, 30")
        elif token_type == "hotp":
            print(f"hotp{num_tokens:04d}{user}, {seed_hex}, hotp, 6")

        else:
            sys.stderr.write("--- Only TOTP Token suppported at the moment!\n")
    except OSError:
        sys.stderr.write(f"-- Nothing for user {user}\n")
