name: reviewdog
on: [pull_request]
jobs:
  misspell:
    name: runner / codespell
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v5
      - name: codespell
        uses: codespell-project/actions-codespell@v2
        with:
          only_warn: 1
          exclude_file: .codespell_skip
