# This workflow builds the Sphinx documentation, and in doing so - checks for errors in the documentation.
name: Docs

on:
  push:
  pull_request:
    types: [ opened, reopened, synchronize ]
  workflow_dispatch:

jobs:
  docs:
    name: Test Docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.5"
          cache: "pip"

      - name: Install Dependencies and Package
        run: |
          python -m pip install -U pip setuptools
          pip install -U -r requirements.txt
          pip install -e .[docs]

      - name: Build Documentation
        run: |
          cd doc
          sphinx-build -b html -j auto -a -n -T -W --keep-going . _build/html
