# This workflow will check for changed files, install Python dependencies and
# run tests with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Docs

on:
  # run on each push to every branch of the repository but only on
  # pull requests to the 'master' and 'branch-*' branches
  push:
  pull_request:
    branches:
      - "*"

jobs:
  build:
    name: 'Build docs'
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        # clone submodules as well
        submodules: 'recursive'

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12


    - name: Install dependencies
      # create the virtual environment
      run: |
        python -m pip install --upgrade pip setuptools
        pip install .[docs]

    - name: Build docs in the CI      
      run: |
        cd doc
        make html
        
