# This workflow will create python packages when the master branch is tagged

name: Python Release

on:
  release:
    types: [published]

jobs:
  build-dist:
    name: Build Python sdist and wheel
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          # clone submodules as well
          submodules: 'recursive'
      - run: mkdir -p dist
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install build environment
        run: >-
          python -m pip install build --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m build --sdist --wheel --outdir dist/

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*